# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockmate < Formula
  desc "Docker container monitoring TUI"
  homepage "https://github.com/shubh-io/DockMate"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.7/dockmate-darwin-amd64"
      sha256 "cf9bd3682fe7e068f5c5f8c647e0ccca247555b22b87c4787d384cc26d26d301"

      def install
        bin.install "dockmate-darwin-amd64" => "dockmate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.7/dockmate-darwin-arm64"
      sha256 "8a61bffdd4544141f910cd41dd772ea261869d5b37ea8d1c7e005dd520e7cd33"

      def install
        bin.install "dockmate-darwin-arm64" => "dockmate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.7/dockmate-linux-amd64"
      sha256 "e61de97434ec7f74bc9307988ec609d1fef0baa61b45af4dc5258caaf789117d"
      def install
        bin.install "dockmate-linux-amd64" => "dockmate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.7/dockmate-linux-arm64"
      sha256 "05d845a003daeb8019b8f6a59cf2be0ef227600ee9cac207543ebbd142c5b836"
      def install
        bin.install "dockmate-linux-arm64" => "dockmate"
      end
    end
  end

  test do
    system "#{bin}/dockmate --version"
  end
end
