# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockmate < Formula
  desc "Docker container monitoring TUI"
  homepage "https://github.com/shubh-io/DockMate"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.12/dockmate-darwin-amd64"
      sha256 "08385b42b2d3eed001df90a867de163a921ba6db99e5c5c5d61b14ffb7b07263"

      def install
        bin.install "dockmate-darwin-amd64" => "dockmate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.12/dockmate-darwin-arm64"
      sha256 "50db639d72a4cb33f8e3e1e0a3a72c8d2d053414f547091222006ca5d73472c6"

      def install
        bin.install "dockmate-darwin-arm64" => "dockmate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.12/dockmate-linux-amd64"
      sha256 "ca19b681fa252fe429dbc393829b821dcf4677c98b21f81f1fb4f3a0f11b8117"
      def install
        bin.install "dockmate-linux-amd64" => "dockmate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubh-io/dockmate/releases/download/v0.0.12/dockmate-linux-arm64"
      sha256 "a344bfa6d2c3e82bd84410895947ad9d8f9363271cf3b279c8d8673c03a6a3eb"
      def install
        bin.install "dockmate-linux-arm64" => "dockmate"
      end
    end
  end

  test do
    system "#{bin}/dockmate --version"
  end
end
